version: "3"
services:
  wecircles:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/go/src/github.com/souhub/wecircles
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    build:
      context: ./test/mysql
      dockerfile: Dockerfile.dev
    ports:
      - "3306:3306"
