version: "3"
services:
  mysql:
    build:
      context: ./test/mysql
      dockerfile: Dockerfile.dev
    # volumes:
    # - ./configs/mysql/conf.d:/etc/mysql/conf.d
    # - ./configs/init:/docker-entrypoint-initdb.d
    #   - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  wecircles:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/go/src/github.com/souhub/wecircles
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    environment:
       AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
       AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
       AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
       WECIRCLES_S3_IMAGE_BUCKET: $WECIRCLES_S3_IMAGE_BUCKET
    command: fresh
    ports:
      - "80:80"
